/* Conversation */
export const CONVERSATION_START = "CONVERSATION_START"
export const CONVERSATION_SUCCESS = "CONVERSATION_SUCCESS"
export const CONVERSATION_ERROR = "CONVERSATION_ERROR"
export const CONVERSATION_RESULT = "CONVERSATION_RESULT"

/* Currency list*/
export const CURRENCY_LIST_START = "CURRENCY_LIST_START"
export const CURRENCY_LIST_SUCCESS = "CURRENCY_LIST_SUCCESS"
export const CURRENCY_LIST_ERROR = "CURRENCY_LIST_ERROR"
export const CURRENCY_LIST_RESULT = "CURRENCY_LIST_RESULT"
